<?php
/**
 * pdf_exports/export_pdf_defects.php
 * Generates a PDF report for defects based on current filters from defects.php.
 */

// Enable output buffering and start session
ini_set('output_buffering', '1');
ob_start();
session_start();

// Authentication check
if (!isset($_SESSION['username']) || !isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// Current date/time in UK format and user info - SAFELY
$current_datetime = date('d/m/Y H:i:s');
$current_user = isset($_SESSION['username']) ? htmlspecialchars($_SESSION['username']) : 'Guest';

// Include required files
require_once 'config/database.php';
require_once 'includes/functions.php'; // Make sure this file defines helper functions
require_once 'tcpdf/tcpdf.php';

// Fallback helper if not defined
if (!function_exists('formatUKDate')) {
    function formatUKDate($date) {
        return date('d/m/Y', strtotime($date));
    }
}

// Get filtering parameters from GET (if any)
$statusFilter = $_GET['status'] ?? 'all';
$priorityFilter = $_GET['priority'] ?? 'all';
$contractorFilter = $_GET['contractor'] ?? 'all';
$projectFilter = $_GET['project'] ?? 'all';
$dateAddedFilter = $_GET['date_added'] ?? '';
$searchTerm = $_GET['search'] ?? '';

// Connect to database
try {
    $database = new Database();
    $db = $database->getConnection();
} catch (Exception $e) {
    die("Database connection error: " . $e->getMessage());
}

// Build base query for defects - KEEP EXISTING TOTAL CALCULATIONS
$query = "SELECT 
                d.id,
                d.title,
                d.created_at,
                d.status,
                d.priority,
                p.name as project_name,
                c.company_name as contractor_name,
                u.username as created_by_user
          FROM defects d
          LEFT JOIN projects p ON d.project_id = p.id
          LEFT JOIN contractors c ON d.assigned_to = c.id
          LEFT JOIN users u ON d.created_by = u.id
          WHERE d.deleted_at IS NULL";

$params = [];

if ($statusFilter !== 'all') {
    $query .= " AND d.status = :status";
    $params[':status'] = $statusFilter;
}

if ($priorityFilter !== 'all') {
    $query .= " AND d.priority = :priority";
    $params[':priority'] = $priorityFilter;
}

if ($contractorFilter !== 'all') {
    $query .= " AND d.assigned_to = :contractor_id";
    $params[':contractor_id'] = $contractorFilter;
}

if ($projectFilter !== 'all') {
    $query .= " AND d.project_id = :project_id";
    $params[':project_id'] = $projectFilter;
}

if (!empty($dateAddedFilter)) {
    $query .= " AND DATE(d.created_at) = :date_added";
    $params[':date_added'] = $dateAddedFilter;
}

if (!empty($searchTerm)) {
    $query .= " AND (d.title LIKE :search OR d.description LIKE :search)";
    $params[':search'] = "%$searchTerm%";
}

$query .= " ORDER BY d.updated_at DESC";

// Execute the query
$stmt = $db->prepare($query);
$stmt->execute($params);
$defects = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Begin building HTML content for PDF output
$html = <<<EOD
<style>
    body { font-family: Helvetica, sans-serif; }
    h1 { text-align: center; }
    table { width: 100%; border-collapse: collapse; font-size: 10pt; }
    th, td { border: 1px solid #ddd; padding: 6px; text-align: center; }
    th { background-color: #007bff; color: #fff; }
    .footer { font-size: 9pt; text-align: center; margin-top: 20px; }
</style>
<h1>Defects Report</h1>
<p>Report generated on: {$current_datetime}</p>
<p>Generated by: {$current_user}</p>
<table>
    <thead>
        <tr>
            <th>Defect No</th>
            <th>Title</th>
            <th>Project</th>
            <th>Contractor</th>
            <th>Status</th>
            <th>Priority</th>
            <th>Created</th>
            <th>Created By</th>
        </tr>
    </thead>
    <tbody>
EOD;

if (!empty($defects)) {
    foreach ($defects as $defect) {
        $html .= "<tr>
                    <td>{$defect['id']}</td>
                    <td>" . htmlspecialchars($defect['title']) . "</td>
                    <td>" . htmlspecialchars($defect['project_name'] ?? '') . "</td>
                    <td>" . htmlspecialchars($defect['contractor_name'] ?? 'Unassigned') . "</td>
                    <td>" . ucfirst(str_replace('_', ' ', $defect['status'])) . "</td>
                    <td>" . ucfirst($defect['priority']) . "</td>
                    <td>" . date('d/m/Y H:i', strtotime($defect['created_at'])) . "</td>
                    <td>" . htmlspecialchars($defect['created_by_user'] ?? 'Unknown') . "</td>
                  </tr>";
    }
} else {
    $html .= "<tr><td colspan='8'>No defects found for the selected filters.</td></tr>";
}
$html .= "</tbody></table>";
$html .= "<div class='footer'>Defect Tracker App &copy; 2025</div>";

// Create PDF using TCPDF
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator('Defect Tracker App');
$pdf->SetAuthor($current_user);
$pdf->SetTitle('Defects Report');
$pdf->SetSubject('Defects Report');

// Remove default header and footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins and auto page breaks
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();

// Write the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF to browser for download
$pdf->Output('Defects_Report_' . date('YmdHis') . '.pdf', 'D');

exit;
?>