<?php
// pdf_exports/export_pdf_reports.php
// Include TCPDF library
require_once($_SERVER['DOCUMENT_ROOT'] . '/tcpdf/tcpdf.php'); // Absolute path

// Get query parameters
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : date('Y-m-d', strtotime('-30 days'));
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : date('Y-m-d');

// Format dates for display in UK format
$display_start_date = date('d/m/Y', strtotime($start_date));
$display_end_date = date('d/m/Y', strtotime($end_date));

// Set current user and datetime for the report header in specified format
$current_datetime = '2025-03-22 12:47:43'; // As specified by user
$current_user = 'irlam'; // As specified by user

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Defect Tracker');
$pdf->SetAuthor($current_user);
$pdf->SetTitle('Contractor Performance Report');
$pdf->SetSubject('Defect Management Report');

// Set default header data
$pdf->setHeaderData('', 0, 'Defect Management Report', 'Period: ' . $display_start_date . ' to ' . $display_end_date);

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', 'B', 16);

// Title
$pdf->Cell(0, 10, 'Contractor Performance Report', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(0, 10, 'Period: ' . $display_start_date . ' to ' . $display_end_date, 0, 1, 'C');
$pdf->Cell(0, 5, 'Current Date and Time: ' . $current_datetime, 0, 1, 'C');
$pdf->Cell(0, 5, 'Generated By: ' . htmlspecialchars($current_user), 0, 1, 'C');

// Connect to database
require_once('../config/database.php');
$database = new Database();
$db = $database->getConnection();

// Get contractor performance data
$contractorPerformanceQuery = "
    SELECT 
        c.id,
        c.company_name,
        c.logo,
        c.trade,
        COUNT(DISTINCT d.id) as total_defects,
        SUM(CASE WHEN d.status = 'open' THEN 1 ELSE 0 END) as open_defects,
        SUM(CASE WHEN d.status = 'pending' THEN 1 ELSE 0 END) as pending_defects,
        SUM(CASE WHEN d.status = 'closed' OR d.status = 'accepted' THEN 1 ELSE 0 END) as closed_defects,
        SUM(CASE WHEN d.status = 'rejected' THEN 1 ELSE 0 END) as rejected_defects,
        SUM(CASE WHEN d.due_date < UTC_TIMESTAMP() AND d.status IN ('open', 'pending') THEN 1 ELSE 0 END) as overdue_defects,
        MAX(d.updated_at) as last_update
    FROM 
        contractors c
        LEFT JOIN defects d ON c.id = d.assigned_to
            AND d.created_at BETWEEN :start_date AND :end_date
    WHERE 
        c.status = 'active'
    GROUP BY 
        c.id, c.company_name, c.logo, c.trade
    HAVING 
        total_defects > 0
    ORDER BY 
        total_defects DESC
";

$stmt = $db->prepare($contractorPerformanceQuery);
$stmt->execute([
    ':start_date' => $start_date . ' 00:00:00',
    ':end_date' => $end_date . ' 23:59:59'
]);
$contractorStats = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Add space before table
$pdf->Ln(10);

// Table header
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(60, 7, 'Contractor', 1, 0, 'C', 1);
$pdf->Cell(15, 7, 'Total', 1, 0, 'C', 1);
$pdf->Cell(15, 7, 'Open', 1, 0, 'C', 1);
$pdf->Cell(15, 7, 'Pending', 1, 0, 'C', 1);
$pdf->Cell(20, 7, 'Overdue', 1, 0, 'C', 1);
$pdf->Cell(20, 7, 'Rejected', 1, 0, 'C', 1);
$pdf->Cell(20, 7, 'Closed', 1, 0, 'C', 1);
$pdf->Cell(25, 7, 'Last Update', 1, 1, 'C', 1);

// Initialize totals
$total_defects = 0;
$total_open = 0;
$total_pending = 0;
$total_overdue = 0;
$total_rejected = 0;
$total_closed = 0;

// Table data
$pdf->SetFont('helvetica', '', 9);
$pdf->SetFillColor(245, 245, 245);
$fill = 0;

foreach ($contractorStats as $stat) {
    // Calculate row height based on content
    $rowHeight = 10;
    
    // Start position for this row
    $nameX = $pdf->GetX();
    $nameY = $pdf->GetY();
    
    // Draw cell border first
    $pdf->Cell(60, $rowHeight, '', 1, 0, 'L', $fill);
    
    // Reset position to add content
    $pdf->SetXY($nameX, $nameY);
    
    // Check if logo exists and is valid
    $hasLogo = false;
    $textIndent = 0;
    $logoWidth = 0;
    
    if (!empty($stat['logo'])) {
        // Handle both old format (uploads/logos/filename.png) and new format (filename.png)
        $logoFilename = $stat['logo'];
        if (stripos($logoFilename, 'uploads/logos/') === 0) {
            $logoFilename = substr($logoFilename, strlen('uploads/logos/'));
        }
        $logoPath = $_SERVER['DOCUMENT_ROOT'] . '/uploads/logos/' . $logoFilename;
        if (file_exists($logoPath) && is_readable($logoPath)) {
            // Get image dimensions to maintain aspect ratio
            $imgInfo = @getimagesize($logoPath);
            if ($imgInfo !== false) {
                // Max logo dimensions
                $maxLogoHeight = 8;
                $maxLogoWidth = 14;
                
                // Calculate new dimensions maintaining aspect ratio
                $originalWidth = $imgInfo[0];
                $originalHeight = $imgInfo[1];
                $aspectRatio = $originalWidth / $originalHeight;
                
                if ($aspectRatio > 1) {
                    // Wider than tall
                    $logoWidth = $maxLogoWidth;
                    $logoHeight = $logoWidth / $aspectRatio;
                    if ($logoHeight > $maxLogoHeight) {
                        $logoHeight = $maxLogoHeight;
                        $logoWidth = $logoHeight * $aspectRatio;
                    }
                } else {
                    // Taller than wide or square
                    $logoHeight = $maxLogoHeight;
                    $logoWidth = $logoHeight * $aspectRatio;
                    if ($logoWidth > $maxLogoWidth) {
                        $logoWidth = $maxLogoWidth;
                        $logoHeight = $logoWidth / $aspectRatio;
                    }
                }
                
                try {
                    // Place logo at the left side with proper dimensions
                    $pdf->Image($logoPath, $nameX + 2, $nameY + ($rowHeight - $logoHeight) / 2, $logoWidth, $logoHeight);
                    $hasLogo = true;
                    $textIndent = $logoWidth + 4; // Indent text based on actual logo width + margin
                } catch (Exception $e) {
                    error_log("PDF Image Error: " . $e->getMessage() . " - Logo path: " . $logoPath);
                }
            }
        }
    }
    
    // Add company name and trade with proper indent if needed
    $pdf->SetXY($nameX + $textIndent, $nameY);
    $pdf->MultiCell(60 - $textIndent, $rowHeight/2, $stat['company_name'], 0, 'L', 0);
    $pdf->SetXY($nameX + $textIndent, $nameY + $rowHeight/2);
    $pdf->MultiCell(60 - $textIndent, $rowHeight/2, $stat['trade'], 0, 'L', 0);
    
    // Reset position for other cells
    $pdf->SetXY($nameX + 60, $nameY);
    
    // Add other data cells
    $pdf->Cell(15, $rowHeight, $stat['total_defects'], 1, 0, 'C', $fill);
    $pdf->Cell(15, $rowHeight, $stat['open_defects'], 1, 0, 'C', $fill);
    $pdf->Cell(15, $rowHeight, $stat['pending_defects'], 1, 0, 'C', $fill);
    $pdf->Cell(20, $rowHeight, $stat['overdue_defects'], 1, 0, 'C', $fill);
    $pdf->Cell(20, $rowHeight, $stat['rejected_defects'], 1, 0, 'C', $fill);
    $pdf->Cell(20, $rowHeight, $stat['closed_defects'], 1, 0, 'C', $fill);
    
    // Format date for last update in UK format (DD/MM/YYYY)
    $last_update = !empty($stat['last_update']) ? 
        date('d/m/Y', strtotime($stat['last_update'])) : 'N/A';
    $pdf->Cell(25, $rowHeight, $last_update, 1, 1, 'C', $fill);
    
    // Accumulate totals
    $total_defects += $stat['total_defects'];
    $total_open += $stat['open_defects'];
    $total_pending += $stat['pending_defects'];
    $total_overdue += $stat['overdue_defects'];
    $total_rejected += $stat['rejected_defects'];
    $total_closed += $stat['closed_defects'];
    
    // Alternate fill color
    $fill = !$fill;
}

// Add totals row
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetFillColor(210, 210, 210);
$pdf->Cell(60, $rowHeight, 'TOTALS', 1, 0, 'R', 1);
$pdf->Cell(15, $rowHeight, $total_defects, 1, 0, 'C', 1);
$pdf->Cell(15, $rowHeight, $total_open, 1, 0, 'C', 1);
$pdf->Cell(15, $rowHeight, $total_pending, 1, 0, 'C', 1);
$pdf->Cell(20, $rowHeight, $total_overdue, 1, 0, 'C', 1);
$pdf->Cell(20, $rowHeight, $total_rejected, 1, 0, 'C', 1);
$pdf->Cell(20, $rowHeight, $total_closed, 1, 0, 'C', 1);
$pdf->Cell(25, $rowHeight, '', 1, 1, 'C', 1);

// Add explanatory note about defect statuses
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(0, 6, 'Defect Status Explanations:', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 9);
$pdf->MultiCell(0, 5, 'Open: Defects that have been reported but not yet addressed.', 0, 'L');
$pdf->MultiCell(0, 5, 'Pending: Defects that have been assigned and are being worked on.', 0, 'L');
$pdf->MultiCell(0, 5, 'Rejected: Defects that have been disputed by the contractor.', 0, 'L');
$pdf->MultiCell(0, 5, 'Closed/Accepted: Defects that have been successfully resolved.', 0, 'L');
$pdf->MultiCell(0, 5, 'Overdue: Open or pending defects that have passed their due date.', 0, 'L');

// Output the PDF
$pdf->Output('contractor_performance_report.pdf', 'I');
?>